-- Phase 5: server-side transactional email pipeline (outbox pattern).
--
-- Business events write a queue row; nothing is sent from the browser. A worker
-- claims rows, renders an approved template and delivers it over SMTP. The design
-- goals are the ones the task list calls for: server-side only, validated
-- recipients, duplicate-send prevention, retry with backoff, failure logging
-- without secret material, and a clean separation from promotional campaigns.
--
-- Authorisation follows the existing pattern in this project: the enqueue
-- functions run as the table owner (SECURITY DEFINER, pinned search_path) because
-- they fire from triggers on INSERT/UPDATE, and the queue itself is readable only
-- by staff under row level security.

create table if not exists public.email_outbox (
  id bigint generated by default as identity primary key,
  -- One queue row per business event occurrence. Inserting the same key twice is
  -- a no-op, so a retried request or a re-firing trigger cannot double-send.
  event_key text not null,
  template text not null check (template in (
    'order_confirmation',
    'payment_confirmation',
    'order_processing',
    'order_shipped',
    'order_delivered',
    'order_cancelled',
    'refund_processed',
    'refund_failed',
    'review_request',
    'abandoned_cart',
    'admin_new_order',
    'admin_payment_verified',
    'admin_refund_requested'
  )),
  recipient_kind text not null default 'customer' check (recipient_kind in ('customer', 'staff')),
  -- Customer mail always carries its own address; staff mail is resolved by the
  -- worker from the deployment's configured inbox, so no address is duplicated
  -- into rows.
  recipient_email text,
  subject text not null,
  payload jsonb not null default '{}'::jsonb,
  order_ref text,
  status text not null default 'pending' check (status in ('pending', 'sending', 'sent', 'failed', 'skipped')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint email_outbox_event_unique unique (event_key),
  constraint email_outbox_recipient_check check (
    (recipient_kind = 'customer' and coalesce(recipient_email, '') ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
    or (recipient_kind = 'staff')
  ),
  constraint email_outbox_attempts_check check (attempts >= 0 and attempts <= 25)
);

create index if not exists idx_email_outbox_claim
  on public.email_outbox (status, next_attempt_at);
create index if not exists idx_email_outbox_order
  on public.email_outbox (order_ref);

alter table public.email_outbox enable row level security;

-- Staff can read the queue (admin visibility + audit trail) but never write it
-- through the API: only the trigger functions and the worker change rows.
drop policy if exists "Staff Read Email Outbox" on public.email_outbox;
create policy "Staff Read Email Outbox" on public.email_outbox
  for select to authenticated
  using (public.is_staff(auth.uid()));

-- ---------------------------------------------------------------------------
-- Enqueue helper
-- ---------------------------------------------------------------------------

create or replace function public.enqueue_email(
  p_event_key text,
  p_template text,
  p_recipient_kind text,
  p_recipient_email text,
  p_subject text,
  p_payload jsonb,
  p_order_ref text default null
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  -- Whitespace-only or over-long keys are bugs, not data: refuse quietly rather
  -- than writing an unusable queue row.
  if p_event_key is null or length(trim(p_event_key)) = 0 or length(p_event_key) > 200 then
    return;
  end if;
  if p_subject is null or length(trim(p_subject)) = 0 then
    return;
  end if;

  insert into public.email_outbox (
    event_key, template, recipient_kind, recipient_email, subject, payload, order_ref
  )
  values (
    trim(p_event_key),
    p_template,
    p_recipient_kind,
    nullif(trim(coalesce(p_recipient_email, '')), ''),
    left(p_subject, 150),
    coalesce(p_payload, '{}'::jsonb),
    p_order_ref
  )
  on conflict (event_key) do nothing;
exception
  -- A queue write must never break the business transaction that caused it: a bad
  -- address format or a duplicate event key is a logging problem, not a reason to
  -- fail a sale. Stagnation is visible in the admin queue view instead.
  when others then
    null;
end;
$$;

alter function public.enqueue_email(text, text, text, text, text, jsonb, text) owner to postgres;
revoke execute on function public.enqueue_email(text, text, text, text, text, jsonb, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Order events
-- ---------------------------------------------------------------------------

create or replace function public.emaillify_order_insert() returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.enqueue_email(
    'order_confirmation:' || new.order_number,
    'order_confirmation',
    'customer',
    new.customer_email,
    'HM Signature — order ' || new.order_number || ' received',
    jsonb_build_object(
      'orderNumber', new.order_number,
      'customerName', new.customer_name,
      'total', new.total,
      'paymentMethod', new.payment_method,
      'shippingCity', coalesce(new.shipping_address ->> 'city', '')
    ),
    new.order_number
  );

  perform public.enqueue_email(
    'admin_new_order:' || new.order_number,
    'admin_new_order',
    'staff',
    null,
    'New order ' || new.order_number || ' — ' || coalesce(new.payment_method, 'payment pending'),
    jsonb_build_object(
      'orderNumber', new.order_number,
      'customerName', new.customer_name,
      'total', new.total,
      'paymentMethod', new.payment_method
    ),
    new.order_number
  );

  return new;
end;
$$;

create or replace function public.emaillify_order_update() returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_currency text := 'PKR';
begin
  -- Payment confirmation: only when the payment state actually reaches Paid.
  if new.payment_status is distinct from old.payment_status
     and lower(new.payment_status) in ('paid', 'verified', 'confirmed') then
    perform public.enqueue_email(
      'payment_confirmation:' || new.order_number,
      'payment_confirmation',
      'customer',
      new.customer_email,
      'HM Signature — payment confirmed for ' || new.order_number,
      jsonb_build_object(
        'orderNumber', new.order_number,
        'customerName', new.customer_name,
        'total', new.total,
        'paymentMethod', new.payment_method
      ),
      new.order_number
    );
  end if;

  -- Order progress. Each status produces its own event key, so a later repeat of
  -- the same status never re-sends.
  if new.status is distinct from old.status then
    case lower(new.status)
      when 'confirmed', 'processing' then
        perform public.enqueue_email(
          'order_processing:' || new.order_number || ':' || new.status,
          'order_processing',
          'customer',
          new.customer_email,
          'HM Signature — preparing order ' || new.order_number,
          jsonb_build_object('orderNumber', new.order_number, 'customerName', new.customer_name, 'status', new.status),
          new.order_number
        );
      when 'shipped', 'out for delivery' then
        perform public.enqueue_email(
          'order_shipped:' || new.order_number || ':' || coalesce(new.tracking_id, 'no-tracking'),
          'order_shipped',
          'customer',
          new.customer_email,
          'HM Signature — order ' || new.order_number || ' is on its way',
          jsonb_build_object(
            'orderNumber', new.order_number,
            'customerName', new.customer_name,
            'courier', coalesce(new.courier_name, 'our delivery team'),
            'trackingId', coalesce(new.tracking_id, ''),
            'trackingUrl', coalesce(new.tracking_url, ''),
            'estimatedDelivery', coalesce(to_char(new.estimated_delivery, 'DD Mon YYYY'), '')
          ),
          new.order_number
        );
      when 'delivered' then
        perform public.enqueue_email(
          'order_delivered:' || new.order_number,
          'order_delivered',
          'customer',
          new.customer_email,
          'HM Signature — order ' || new.order_number || ' delivered',
          jsonb_build_object('orderNumber', new.order_number, 'customerName', new.customer_name),
          new.order_number
        );
        -- Review request is a separate event with its own key so it can be
        -- scheduled independently and never duplicates the delivery notice.
        perform public.enqueue_email(
          'review_request:' || new.order_number,
          'review_request',
          'customer',
          new.customer_email,
          'How does ' || coalesce(new.customer_name, 'your') || ', does the scent feel like yours?',
          jsonb_build_object('orderNumber', new.order_number, 'customerName', new.customer_name),
          new.order_number
        );
      when 'cancelled' then
        perform public.enqueue_email(
          'order_cancelled:' || new.order_number,
          'order_cancelled',
          'customer',
          new.customer_email,
          'HM Signature — order ' || new.order_number || ' cancelled',
          jsonb_build_object(
            'orderNumber', new.order_number,
            'customerName', new.customer_name,
            'total', new.total,
            'paymentMethod', new.payment_method
          ),
          new.order_number
        );
      else
        null;
    end case;
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Refund events
-- ---------------------------------------------------------------------------

create or replace function public.emaillify_refund_update() returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_email text;
  v_number text;
  v_name text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  select o.customer_email, o.order_number, o.customer_name
    into v_email, v_number, v_name
  from public.orders o
  where o.id = new.order_id;

  if v_email is null then
    return new;
  end if;

  if lower(new.status) = 'processed' then
    perform public.enqueue_email(
      'refund_processed:' || new.id::text,
      'refund_processed',
      'customer',
      v_email,
      'HM Signature — refund of ' || new.amount::text || ' for ' || coalesce(v_number, ''),
      jsonb_build_object(
        'orderNumber', coalesce(v_number, ''),
        'customerName', coalesce(v_name, ''),
        'amount', new.amount,
        'currency', new.currency,
        'reference', coalesce(new.refund_reference, '')
      ),
      v_number
    );
  elsif lower(new.status) in ('failed', 'rejected') then
    perform public.enqueue_email(
      'refund_failed:' || new.id::text,
      'refund_failed',
      'customer',
      v_email,
      'HM Signature — refund could not be completed for ' || coalesce(v_number, ''),
      jsonb_build_object(
        'orderNumber', coalesce(v_number, ''),
        'customerName', coalesce(v_name, ''),
        'amount', new.amount,
        'reason', left(coalesce(new.notes, ''), 300)
      ),
      v_number
    );
  end if;

  return new;
end;
$$;

create or replace function public.emaillify_refund_insert() returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.enqueue_email(
    'admin_refund_requested:' || new.id::text,
    'admin_refund_requested',
    'staff',
    null,
    'Refund requested on ' || coalesce(new.refund_reference, new.id::text),
    jsonb_build_object('amount', new.amount, 'currency', new.currency, 'reason', left(coalesce(new.reason, ''), 200)),
    null
  );
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

drop trigger if exists trg_email_orders_insert on public.orders;
create trigger trg_email_orders_insert
  after insert on public.orders
  for each row execute function public.emaillify_order_insert();

drop trigger if exists trg_email_orders_update on public.orders;
create trigger trg_email_orders_update
  after update of status, payment_status, tracking_id on public.orders
  for each row execute function public.emaillify_order_update();

drop trigger if exists trg_email_refunds_insert on public.refunds;
create trigger trg_email_refunds_insert
  after insert on public.refunds
  for each row execute function public.emaillify_refund_insert();

drop trigger if exists trg_email_refunds_update on public.refunds;
create trigger trg_email_refunds_update
  after update of status on public.refunds
  for each row execute function public.emaillify_refund_update();

-- ---------------------------------------------------------------------------
-- Worker primitives: claim, finish, stats
-- ---------------------------------------------------------------------------

-- Claim a batch for delivery. SKIP LOCKED means two overlapping worker invocations
-- can never hand out the same row, and the status flip makes the claim durable.
create or replace function public.claim_email_batch(p_limit integer default 10)
returns setof public.email_outbox
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_limit is null or p_limit < 1 then
    p_limit := 1;
  end if;
  if p_limit > 50 then
    p_limit := 50;
  end if;

  return query
  with picked as (
    select e.id
    from public.email_outbox e
    where e.status in ('pending', 'failed')
      and e.next_attempt_at <= now()
    order by e.created_at
    for update of e skip locked
    limit p_limit
  )
  update public.email_outbox e
  set status = 'sending',
      attempts = e.attempts + 1,
      updated_at = now()
  from picked
  where e.id = picked.id
  returning e.*;
end;
$$;

-- Record the outcome. Error text is truncated and is expected to be a transport
-- reason, never a credential or a payload dump.
create or replace function public.finish_email_send(
  p_id bigint,
  p_status text,
  p_error text default null
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_status not in ('sent', 'failed', 'skipped') then
    raise exception 'Unsupported email outcome.';
  end if;

  update public.email_outbox e
  set status = p_status,
      sent_at = case when p_status = 'sent' then now() else e.sent_at end,
      last_error = left(nullif(trim(coalesce(p_error, '')), ''), 300),
      -- Exponential backoff capped at six hours; a permanent failure simply stops
      -- being claimed once attempts run out.
      next_attempt_at = case
        when p_status = 'failed' then now() + (least(power(2.0, e.attempts)::int, 360) * interval '1 minute')
        else e.next_attempt_at
      end,
      updated_at = now()
  where e.id = p_id
    -- Only a row this worker still holds may be finished.
    and e.status = 'sending';
end;
$$;

-- Staff-facing queue health, used by the admin notification centre. Runs as the
-- caller on purpose: row level security then decides who sees any count at all,
-- so a customer simply gets zero rows.
create or replace function public.get_email_queue_stats()
returns table (queue_status text, row_count bigint, oldest_pending timestamptz)
language sql
stable
set search_path = public, pg_temp
as $$
  select e.status, count(*)::bigint, min(e.created_at) filter (where e.status in ('pending', 'failed'))
  from public.email_outbox e
  group by e.status
  order by e.status;
$$;

alter function public.claim_email_batch(integer) owner to postgres;
alter function public.finish_email_send(bigint, text, text) owner to postgres;
alter function public.get_email_queue_stats() owner to postgres;

-- Never callable from the browser: the worker uses the service-role connection
-- (which owns the objects, so RLS and these grants do not apply to it) and staff
-- read the queue through the table policy instead.
revoke execute on function public.claim_email_batch(integer) from public, anon, authenticated;
revoke execute on function public.finish_email_send(bigint, text, text) from public, anon, authenticated;
revoke execute on function public.get_email_queue_stats() from public, anon, authenticated;
grant execute on function public.get_email_queue_stats() to authenticated;

comment on table public.email_outbox is
  'Transactional email queue written by business-event triggers and drained by api/email-worker. Never holds credentials; promotional campaigns do not use this table.';
comment on column public.email_outbox.event_key is
  'Idempotency key: one queue row per business event occurrence, so retried requests and re-firing triggers cannot double-send.';
comment on column public.email_outbox.recipient_kind is
  'customer = stored address validated by check constraint; staff = resolved by the worker from STORE_CONTACT_EMAIL.';
